# -*- coding: utf-8 -*-
"""recommendation_system.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nCYXrnXYM1CPK4snXJyQMJx1cAiZLSi2
"""

"""
Movie Recommendation System
Content-Based Filtering using Python, Pandas, and Scikit-learn
"""

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# ------------------
# 1. Create Dataset
# ------------------
movies = {
    "title": [
        "Avatar", "Titanic", "The Avengers", "Guardians of the Galaxy",
        "Interstellar", "Inception", "The Dark Knight",
        "John Carter", "Star Trek", "Doctor Strange", "Black Panther"
    ],
    "genres": [
        "Action Adventure Sci-Fi",
        "Drama Romance",
        "Action Superhero Marvel",
        "Action Adventure Sci-Fi",
        "Sci-Fi Drama",
        "Action Sci-Fi Thriller",
        "Action Crime Drama",
        "Action Adventure Sci-Fi",
        "Adventure Sci-Fi",
        "Action Fantasy Marvel",
        "Action Adventure Marvel"
    ],
    "keywords": [
        "alien future world",
        "ship love tragedy",
        "heroes earth battle",
        "space galaxy heroes",
        "space future science",
        "dream subconscious mind",
        "batman joker gotham",
        "mars alien world",
        "space exploration crew",
        "magic superhero dimensions",
        "wakanda king hero"
    ],
    "cast": [
        "Sam Worthington Zoe Saldana",
        "Leonardo DiCaprio Kate Winslet",
        "Robert Downey Jr Chris Evans",
        "Chris Pratt Zoe Saldana",
        "Matthew McConaughey Anne Hathaway",
        "Leonardo DiCaprio Tom Hardy",
        "Christian Bale Heath Ledger",
        "Taylor Kitsch Lynn Collins",
        "Chris Pine Zachary Quinto",
        "Benedict Cumberbatch Rachel McAdams",
        "Chadwick Boseman Michael B. Jordan"
    ],
    "director": [
        "James Cameron",
        "James Cameron",
        "Joss Whedon",
        "James Gunn",
        "Christopher Nolan",
        "Christopher Nolan",
        "Christopher Nolan",
        "Andrew Stanton",
        "J.J. Abrams",
        "Scott Derrickson",
        "Ryan Coogler"
    ]
}

movies_data = pd.DataFrame(movies)


# ------------------
# 2. Preprocessing
# ------------------
features = ["genres", "keywords", "cast", "director"]

for feature in features:
    movies_data[feature] = movies_data[feature].fillna("")


# Combine features into a single string
combined_features = (
    movies_data["genres"] + " " +
    movies_data["keywords"] + " " +
    movies_data["cast"] + " " +
    movies_data["director"]
)


# -----------------------------
# 3. Vectorization + Similarity
# -----------------------------
vectorizer = CountVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)

similarity = cosine_similarity(feature_vectors)


# -----------------------------
# 4. Recommendation Function
# -----------------------------
def recommend_movies(movie_name, top_n=10):
    movie_name = movie_name.lower()

    movies_data["lower_title"] = movies_data["title"].str.lower()

    matching_movies = movies_data[
        movies_data["lower_title"].str.contains(movie_name, na=False)
    ]

    if matching_movies.empty:
        print("\n Movie not found in dataset.")
        return

    movie_index = matching_movies.index[0]

    similarity_scores = list(enumerate(similarity[movie_index]))

    sorted_movies = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    print("\n Top Recommended Movies:\n")

    count = 1
    for movie in sorted_movies[1:top_n + 1]:
        index = movie[0]
        print(f"{count}. {movies_data.iloc[index]['title']}")
        count += 1


# ----------------------
# 5. Main Program
# -----------------------
if __name__ == "__main__":
    print("====================================")
    print(" Movie Recommendation System ")
    print("====================================")

    user_movie = input("\nEnter a movie name: ")
    recommend_movies(user_movie)